#!/bin/bash
export LD_PRELOAD=/opt/cray/pe/lib64/libmpich_gnu_51.so.3:/usr/common/software/darshan/3.1.4/lib/libdarshan.so:$LD_PRELOAD
export PMI_NO_FORK=1
export PMI_NO_PREINITIALIZE=1
module load darshan
module load python/2.7-anaconda-4.4
srun -n 10 python-mpi mpi_write_all.py
