#!/bin/bash
module load cray-petsc/3.6.1.0
module load cray-hdf5-parallel/1.8.16
module load cray-netcdf-hdf5parallel/4.3.3.1
module load python/2.7-anaconda 
module load latex/2015
module load darshan
module load cray-libsci/16.09.1
module load git/2.9.1 



#darshan 3.1.14 caused the problem, --enable-HDF5-pre-1.10
